# Generated by Django 4.1.2 on 2022-10-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='RAM',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
